baseurl: ""
url: ""

title: "Pat Little"
description: "A professional blog about product, technology, and creativity."

permalink: /blog/:title/

collections:
  pages:
    output: true

markdown: kramdown

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Pat Little"
      featured: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
